name: dartiverse_search
description: Simple serverside Dart search-engine aggregater, that makes it
  possible to search GitHub and StackOverflow for dart-related items. The Demo
  contains a web-interface for performing searches.
dependencies:
  http_server: ">=0.9.0 <0.10.0"
  http: ">=0.9.0 <0.10.0"
  route: ">=0.4.0 <0.5.0"
  logging: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
